### ISSUE TITLE
Analytics Cookies Section not responsive

### ISSUE THREAD

**Issue by panseit** [orestbida/cookieconsent#31] opened 2021-05-28 05:22 UTC
Hello,

First of all thank you for the plugin!! It's really helpful and lightweight!
Secondly I am facing the problem/bug below. The Analytics Cookies Section in the Change Preferences section isn't responsive (regarding the Privacy Links).

![Analytics_Section](https://user-images.githubusercontent.com/1145840/119933992-c74df100-bf8d-11eb-9501-0c090e922287.PNG)

Thank you very much!

**Comment by orestbida** [comment] 2021-05-28 09:47
Hi @panseit ,

this is caused by the lengthy url since the browser doesn't know where to "word-break" as it is a single super long string.
This can be fixed by setting the `word-break: break-all;` css rule. By default it is not set as it would cause the text in all the cells to break in weird ways.

you can fix your specific case by either applying a css rule for the `n-th` column of the table (in your case it's the 6-th column), or also in your case `last-child`.

So adding something like this should do the trick:

```css
.cc_div tbody td:last-child{
    word-break: break-all;
}
```

That being said, today I'll release a minor version bump which will allow users to actually **use html inside table cells**. To give them  finer control/customization and also, related to  your case too, allow for a proper `clickable link`:

```javascript
cookie_table: [
    {
        col1: '_ga',
        col2: '<a href="www.google.com" style="word-break: break-all;">thisIsASuperLongStringWhichNeedsTheWordBreakCssRule</a>',
        col3: "bla bla"
       ...
    }
```

Tip: you're using quite a lot of columns so the text looks very busy/crammed, also the modal not being much wide doesn't help with it. Consider for example deleting the 'Type' column. You could specify the type into the description column: "Permanent cookie used to distinguish users"

**Comment by panseit** [comment] 2021-05-28 09:51
Thank you very much for the answer and the tip!! It's my first web project and haven't worked with cookies before so I used your template as it. I will delete the column and modify the description! Thank you again!!

**Closed** 2021-05-28 11:04 UTC

**Comment by panseit** [comment] 2021-05-28 11:18
Thank you!!!
