### ISSUE TITLE
Bug: plugin is executed twice inside the `useEffect` hook in a React

### ISSUE THREAD

**Issue by Polynook** [orestbida/cookieconsent#383] opened 2022-09-30 22:13 UTC
**Version 3.0.0-rc.5**

What is the correct way to use the API?

The way I do it is import it like shown in the docs:
`import * as CookieConsent from 'vanilla-cookieconsent';`

Then I try to call either `CookieConsent.acceptCategory('analytics')` or `CookieConsent.acceptService('ga', 'analytics')` on button click. The cookie gets added, its timestamp is updated, but "categories" and "services" arrays are empty.

Setting categories and services via the modal works fine.

Also, when accessing imported `CookieConsent`, typescript complains: _"Cannot use namespace 'CookieConsent' as a value."_ I have to cast it as `CookieConsent.CookieConsentAPI` for typescript to stop complaining.

**Comment by iamfredrik** [comment] 2022-10-01 10:24
I use the API this way with Next.js:

```
import { useEffect, createContext, useContext } from "react"
import "vanilla-cookieconsent/dist/cookieconsent.js"
import "vanilla-cookieconsent/dist/cookieconsent.css"

const CookieContext = createContext();

const CookieConsentProvider = ({ children, locale }) => {
  const cc = window.initCookieConsent();
  useEffect(() => {
    cc.run({
       // your config goes here
    });
  }, [locale]);

    return (
        <CookieContext.Provider value={{ cc }}>
            {children}
        </CookieContext.Provider>
    );
}

export default CookieConsentProvider

export function useCookie() {
    const context = useContext(CookieContext);
    if (context === undefined) {
      throw new Error('Context must be used within a Provider');
    }
    return context;
}
```

Then in my page component:

```
const CookieConsentProvider = dynamic(() => import('components/CookieConsentProvider'), {
  ssr: false,
})

export default function Page() {
return (
    <CookieConsentProvider locale={locale}>
       <Layout>
       </Layout>
    </CookieConsentProvider>
  )
}
```

Then in any child component I can do the following:

```
import { useCookie } from 'components/CookieConsentProvider'

const MyComponent = () => {
   const { cc } = useCookie()

  const handleClick = () => {
     cc.accept('marketing')
  }
}
```

**Comment by orestbida** [comment] 2022-10-01 13:53
@Polynook 

that is indeed the proper way to use the plugin. 

I believe this issue is caused by React's new `useEffect` behaviour; the `useEffect` hook is executed twice in dev/strict mode and messes up the plugin.

As for the types issue, it has already been fixed in the v3 branch https://github.com/orestbida/cookieconsent/commit/93ccc795406f9c42528d22c8a17da890d2857f30.

**Comment by orestbida** [comment] 2022-10-01 14:29
Released [v3.0.0-rc.6](https://github.com/orestbida/cookieconsent/releases/tag/v3.0.0-rc.6), feel free to re-open this issue if you still encounter the problem.

**Closed by orestbida** 2022-10-01 14:29 UTC
Labels: bug

**Comment by itsam** [comment] 2022-10-01 19:00
> I use the API this way with Next.js:
> 
> ```
> import { useEffect, createContext, useContext } from "react"
> import "vanilla-cookieconsent/dist/cookieconsent.js"
> import "vanilla-cookieconsent/dist/cookieconsent.css"
> 
> const CookieContext = createContext();
> 
> const CookieConsentProvider = ({ children, locale }) => {
>   const cc = window.initCookieConsent();
>   useEffect(() => {
>     cc.run({
>        autorun: true,
>        current_lang: locale,
>        autoclear_cookies: true,
>        page_scripts: true,
>        // your config goes here
>     });
>   }, [locale]);
> 
>     return (
>         <CookieContext.Provider value={{ cc }}>
>             {children}
>         </CookieContext.Provider>
>     );
> }
> 
> export default CookieConsentProvider
> 
> export function useCookieConsent() {
>     const context = useContext(CookieContext);
>     if (context === undefined) {
>       throw new Error('Context must be used within a Provider');
>     }
>     return context;
> }
> ```
> 
> Then in my page component:
> 
> ```
> const CookieConsentProvider = dynamic(() => import('components/CookieConsentProvider'), {
>   ssr: false,
> })
> 
> export default function Page() {
> return (
>     <CookieConsentProvider locale={locale}>
>        <Layout>
>          ...
>        </Layout>
>     </CookieConsentProvider>
>   )
> }
> ```
> 
> Then in any child component I can do the following:
> 
> ```
> import { useCookieConsent } from 'components/CookieConsentProvider'
> 
> const MyComponent = () => {
>    const { cc } = useCookieConsent()
> 
>   const handleClick = () => {
>      cc.accept('marketing')
>   }
> }
> ```

Hello, since you are already using this in next.js...
I have copied your structure, everything works as expected on first load BUT after that (when I navigate in another page) when I call `cc.showSettings(0)` in my component (e.g. Footer), although the settings appear, I got the error below

```
Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'setAttribute')
``` 
Can you please, try also on your code please and let me know if you are facing the same problem? If not, how exactly are you handling "show cookie settings" correctly in every page?

Thank you in advance

**Comment by iamfredrik** [comment] 2022-10-01 19:40
> Hello, since you are already using this in next.js... I have copied your structure, everything works as expected on first load BUT after that (when I navigate in another page) when I call `cc.showSettings(0)` in my component (e.g. Footer), although the settings appear, I got the error below
> 
> ```
> Unhandled Runtime Error
> TypeError: Cannot read properties of undefined (reading 'setAttribute')
> ```
> 
> Can you please, try also on your code please and let me know if you are facing the same problem? If not, how exactly are you handling "show cookie settings" correctly in every page?
> 
> Thank you in advance

Hello, that happens if you don't import it dynamically or if you initialize it twice. Import using the following line and make sure that cc.run is only run once.

```
const CookieConsentProvider = dynamic(() => import('components/CookieConsentProvider'), {
  ssr: false,
})

```

**Comment by iamfredrik** [comment] 2022-10-01 20:17
Btw, I use the stable version 2.8.6. I suppose 3.0.0-rc.5 should work the same way, but I have not tried it.

**Comment by iamfredrik** [comment] 2022-10-01 20:35
I see that cc is missing from the useEffect dependency array in my example, but that should not cause the problem. If you have several page components you may need to move the CookieConsentProvider higher up so that you don't initialize it several times. I'm only using the [...slug] page component.

**Comment by itsam** [comment] 2022-10-01 22:28
I ensured that cc.run inside useEffect runs only once, by using useRef

```
import { useEffect, createContext, useContext, useRef } from "react";
import "vanilla-cookieconsent/dist/cookieconsent.js";
import "vanilla-cookieconsent/dist/cookieconsent.css";

const CookieContext = createContext();

const CookieConsentProvider = ({ children, locale }) => {
  const ccRunRef = useRef(false);
  const cc = window.initCookieConsent();
  useEffect(() => {
    if (ccRunRef.current) return;
    ccRunRef.current = true;

    console.log("cc run !!!");
    cc.run({
      autorun: true,
      current_lang: locale || "el",
      autoclear_cookies: true,
      page_scripts: true,
      //OTHER CONFIGURATIONS HERE
    });
  }, [cc, locale]);

  return (
    <CookieContext.Provider value={{ cc }}>{children}</CookieContext.Provider>
  );
};

export default CookieConsentProvider;

export function useCookieConsent() {
  const context = useContext(CookieContext);
  if (context === undefined) {
    throw new Error("Context must be used within a Provider");
  }
  return context;
}

```
Indeed, I can see the string "cc run !!!" just once now. Still the bug is not solved.

in `_app.js` I am importing the above file as

```
import dynamic from "next/dynamic";
const CookieConsentProvider = dynamic(
  () => import("../providers/cookieConsentProvider"),
  {
    ssr: false,
  }
);

const queryClient = new QueryClient();

function MyApp({ Component, pageProps }) {
  return (
    <QueryClientProvider client={queryClient}>
      <CookieConsentProvider locale={"el"}>
        <AuthProvider>
          <ChakraProvider theme={theme}>
            <SkipNavLink id="skip-nav" style={{ zIndex: 3, top: 5, left: 5 }}>
              Skip to content
            </SkipNavLink>
            <FlashMessage />

            {Component.requireAuth ? (
              <AuthGuard>
                <Component {...pageProps} />
              </AuthGuard>
            ) : (
              // public page
              <Component {...pageProps} />
            )}
            <ReactQueryDevtools initialIsOpen={false} />
          </ChakraProvider>
        </AuthProvider>
      </CookieConsentProvider>
    </QueryClientProvider>
  );
}

export default MyApp;

```

In my <Footer /> component 

```
import { useCookieConsent } from "../providers/cookieConsentProvider";

function Footer() {
  const { cc } = useCookieConsent();
  return (
.....

            <Link as="button" data-cc="c-settings">
              cookies settings version 1
            </Link>
            <Link as="button" onClick={() => cc.showSettings(0)}>
              cookies settings version 2
            </Link>
.....);
}
```

On first load both links works.
After changing page, first link does nothing, second link throws `TypeError: Cannot read properties of undefined (reading 'setAttribute')`

I am using stable 2.8.6 as well.

**Comment by itsam** [comment] 2022-10-01 22:30
I have also used zustand instead of Context, but as expected the same error still appears

**Comment by iamfredrik** [comment] 2022-10-02 02:07
That’s strange. Can you reproduce the error on a new create-next-app without the rest of your configuration?

**Comment by iamfredrik** [comment] 2022-10-02 05:38
I was able to reproduce the problem using next/router. My project doesn't use next/router and reloads every page so that's why it works. I will try to see if I can come up with a fix.

**Comment by iamfredrik** [comment] 2022-10-02 06:27
I think the same problem is described here https://github.com/orestbida/cookieconsent/issues/315#issue-1260790669

**Comment by itsam** [comment] 2022-10-02 09:17
> I was able to reproduce the problem using next/router. My project doesn't use next/router and reloads every page so that's why it works. I will try to see if I can come up with a fix.

Thank you @iamfredrik. Your effort is much appreciated :)

**Comment by iamfredrik** [comment] 2022-10-02 11:26
> Thank you @iamfredrik. Your effort is much appreciated :)

You're welcome. Alas I can't figure this out so we may need help from the developer. The error only comes on first run after switching route. After closing the error dialog it works when switching routes back and forth.

**Comment by orestbida** [comment] 2022-10-02 13:49
@itsam,

I'm not sure I understand the issue (it looks to me that its unrelated to this one), but since you're talking about next.js, here are 2 example configurations that might help:

basic:
https://codesandbox.io/s/cookieconsent-v3-next-js-wkxn6l

access the plugin from any page:
https://stackblitz.com/edit/nextjs-epd84e

If none of the demos are of help, please create a new discussion/issue with a live example that I can inspect.

**Comment by iamfredrik** [comment] 2022-10-03 06:50
Thank you @orestbida. I made a next.js example without typescript using context instead of props: https://stackblitz.com/edit/nextjs-j1kwcf

**Comment by itsam** [comment] 2022-10-03 09:38
I see that all examples are using v3.0, so maybe the problem only occurs in stable 2.8.6...
I am doing the transition to v3 and let you know.
Thanks

**Comment by iamfredrik** [comment] 2022-10-03 09:42
> I see that all examples are using v3.0, so maybe the problem only occurs in stable 2.8.6...
> I am doing the transition to v3 and let you know.
> Thanks

Yes, it seems that v3.0 is required to get it to work properly.

**Comment by itsam** [comment] 2022-10-03 13:36
> > s, it seems that v3.0 is required to get it to work properly.
> 
> Not really. React 18 made things just a little more "complicated", especially for iife + client only plugins such cookieconsent v2.
> 
> @itsam, this is the easiest way to use v2 in next.js (call api via the window object): https://stackblitz.com/edit/nextjs-euxk9k?file=components%2FCookieConsentComponent.js
> 
> I'll update the `FAQ -> How to use in React` section for future users.

You are, right, in the proposed solution, everything works as expected in stable release 2.8.6. I think the tricky part (besides limiting to load just once in the useEffect) was to use `window` (e.g. `window.CookieConsentApi.showSettings(0)`) all the times instead of the object (e.g. cc) which either created once in the context, zustand or  wherever. 

Thanks a lot for clarifying and giving a functional example, I am pretty sure it will be helpful for others trying to integrate with next.js
