### ISSUE TITLE
Floating button after user interaction 

### ISSUE THREAD

**Issue by CasualRascal** [orestbida/cookieconsent#210] opened 2022-01-20 08:35 UTC
I believe there should be a simple but required enhancement to the default themes:

The EU law says that users should easily have access to their cookie preferences to be able to view and update their consent, by rejecting or accepting more than previously.

Therefore I believe that a floating button, which should appear after the plugin is dismissed by the user, should ship with the default styles.

Examples of this behavior can be seen on solutions provided by consent management saas like axeptio, iubenda, cookiebot, etc.

**Comment by mastum** [comment] 2022-01-20 09:07
> The EU law says that users should easily have access to their cookie preferences to be able to view and update their consent, by rejecting or accepting more than previously.

You can just add one button

`<button type="button" aria-label="View cookie settings" data-cc="c-settings">Cookie Settings</button>	`

Or a link
`<a data-cc="c-settings">Cookie Settings</a>`

See FAQ
https://github.com/orestbida/cookieconsent#faq

**Comment by orestbida** [comment] 2022-01-20 12:06
@CasualRascal,

this is a duplicate of #111.

If such a feature were to be added, then I would also need to add options for positioning, modal layout and possibly a custom icon and in my opinion it is not worth it (currently) since the aim of the plugin is to be as lightweight as possible. Nevertheless, you can still achieve this as noted by @mastum.

**Closed by orestbida** 2022-01-20 12:06 UTC
