### ISSUE TITLE
[Feat]: partytown support

### ISSUE THREAD

**Issue by ditto-vlad** [orestbida/cookieconsent#554] opened 2023-08-01 17:23 UTC
### Description

[PartyTown](https://partytown.builder.io/) is a library which lets you handle loading scripts off the main thread in separate workers. This can help speed up your site.

Partytown depends on the `type="text/partytown"` attribute.
CookieConsent relies on `type="text/plain"` to work.

### Proposed solution

The script needs to update from `type="text/plain"` to `type="text/partytown"`.
When this is done dynamically `window.dispatchEvent(new CustomEvent('ptupdate'));` needs to be run.

**Comment by orestbida** [comment] 2023-08-01 21:55
Duplicate of https://github.com/orestbida/cookieconsent/issues/487.

You can use the `data-type` to specify a custom type:

```html
<script type="text/plain" data-type="text/partytown" data-cookiecategory="analytics">
    console.log("executed");
</script>
```

**Comment by ditto-vlad** [comment] 2023-08-02 07:41
My apologies - will test this out and close it if all is good.

Really awesome project, keep up the great work!

**Closed** 2023-08-02 13:11 UTC
Labels: duplicate
