### ISSUE TITLE
Add a button to close the banner

### ISSUE THREAD

**Issue by ondequadre** [orestbida/cookieconsent#216] opened 2022-01-21 13:13 UTC
It is possible to add a button for example with an X to close the banner and accept only the necessary cookies?

Similar to the one present in the settings window?

**Comment by orestbida** [comment] 2022-01-21 21:46
Hi @ondequadre,

short answer: yes.

closing this issue as it is a duplicate of #187.

**Closed by orestbida** 2022-01-21 21:46 UTC
