### ISSUE TITLE
[Bug]: Debugging logs

### ISSUE THREAD

**Issue by zangab** [orestbida/cookieconsent#520] opened 2023-05-19 08:01 UTC
### Expected Behavior

I don't want any debugging logs in my production environment, like 

```
CookieConsent [NOTICE]: ask for consent!  
CookieConsent [MODAL]: show consent_modal
```

Errors are fine, but no debugging logs. I want to have a flag to en- or disable them. Currently `ENABLE_LOGS` is initially set to `true` but never re-set. So in the `_log` function, this `ENABLE_LOGS` is quite needless as it's true anyway. 

### Current Behavior

Debugging logs pollute the console. Also the config is printed.

### Steps to reproduce

Install consent, run it, open browser console.

### Version

2.9.0

### On which browser do you see the issue?

Firefox, Chrome, Safari, Microsoft Edge, Other

**Comment by orestbida** [comment] 2023-05-19 09:00
Duplicate of #12  and #163.

**Comment by zangab** [comment] 2023-05-22 16:42
ah, ok ......
still, this is a bad design imho. why would I need to change the source of my `import` just for debugging?
in my dev environment, I want to debug the stuff (no minifcation, source maps etc). if I am supposed to import the dist version everyone needs to know that there's such option to do that. can't name any package that's handling it this way.

**Comment by orestbida** [comment] 2023-05-28 00:20
I agree that having logs enabled only in the `src` version is not the best approach, but I also believe that users should know the difference between `dist` and `src`. There are instances where the `src` version may not be usable at all, e.g. if it is written in TypeScript and requires compilation.

Nonetheless, I will update the readme and explicitly instruct users to use the `dist` version.

**Comment by orestbida** [comment] 2023-05-31 02:42
The second step of the [Installation & usage](https://github.com/orestbida/cookieconsent/tree/v2.9#installation--usage) section now explicitly specifies the usage of the `dist` version.

**Closed by orestbida** 2023-05-31 02:42 UTC
Labels: documentation, duplicate, wontfix
