### ISSUE TITLE
Add a function to reconsider consent (window with link to open full consent window)

### ISSUE THREAD

**Issue by strakadavid** [orestbida/cookieconsent#172] opened 2021-12-31 08:59 UTC
After user make his decision - you should display small windows or link to change user consent settings. This is one of GDPR requirements missing in your solution.

Function "revisit" is not good for this function, because is showing all the time full consent window.

Thank you!

**Comment by orestbida** [comment] 2021-12-31 12:24
Hi @strakadavid ,

you can can configure any link/button to open the settings modal by simply specifying this attribute: `data-cc="c-settings"`.

Example:
```html
<a href="javascript:void(0);" aria-label="View cookie settings" data-cc="c-settings">View Cookie Settings</a>
```
Closing this issue since it is a duplicate of #111.

**Closed by orestbida** 2021-12-31 12:24 UTC
